language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env update -q -f envs/mamba.yaml
  - conda activate mamba
  - travis_wait 30 mamba env create -q -f tests/files/testing_env.yaml -n testing_env
  - conda activate testing_env
script: 
  - travis_wait 60 bats tests/test_juno-typing.bats
