__package_name__ = "juno_typing"
__authors__ = "Alejandra Hernández Segura, Karim Hajji and Roxanne Wolthuis"
__email__ = "roxanne.wolthuis@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.8.7"
__description__ = "Juno Typing has incorporates many tools to type bacteria."
