__package_name__ = "juno_assembly"
__authors__ = "Alejandra Hernández Segura and Karim Hajji"
__email__ = "karim.hajji@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.5.2"
__description__ = "Juno Typing has incorporates many tools to type bacteria."
