# General pipeline
sample_sheet: "sample_sheet.yaml" 

# Pipeline parameters
threads:
  cgemlst: 1
  kmerfinder: 1
  seqsero2: 6
  serotypefinder: 2
  seroba: 1
mem_mb:
  cgemlst: 4000
  kmerfinder: 4000
  seqsero2: 5000
  serotypefinder: 8000
  seroba: 8000
