# Resources
threads:
  cgemlst: 1
  kmerfinder: 1
  seqsero2: 6
  serotypefinder: 2
  seroba: 1
mem_gb:
  other: 4
  cgemlst: 10
  kmerfinder: 10
  seqsero2: 10
  serotypefinder: 10
  seroba: 10

# Pipeline parameters (not taken from user)
salmonellamonophasic:
  min_cov: 10
