# Resources
threads:
  cgemlst: 1
  kmerfinder: 1
  seqsero2: 6
  serotypefinder: 2
  seroba: 1
mem_mb:
  cgemlst: 12000
  kmerfinder: 12000
  seqsero2: 24000
  serotypefinder: 12000
  seroba: 12000

# Pipeline parameters (not taken from user)
salmonellamonophasic:
  min_cov: 12000
