# Testing for pipeline python wrapper and scripts used inside rules
# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Juno_typing test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: ubuntu-20.04}
          - {os: ubuntu-latest}
    name: Testing Juno_typing ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: envs/master_env.yaml
          channel-priority: true
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test the python wrapper using base_juno_pipeline.
        shell: bash -l {0}
        run: python ./tests/test_juno-typing.py
      - name: Test the individual scripts used inside the snakemake rules.
        shell: bash -l {0}
        run: python ./tests/test_scripts_used_in_rules.py
