# BATS testing for python wrapper
# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Juno-typing pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: macOS-latest}
          - {os: ubuntu-18.04}
          - {os: ubuntu-latest}
    name: Testing python wrapper ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setting up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge, anaconda, bioconda, biocore, defaults
          channel-priority: true
          environment-file: envs/master_env.yaml 
          activate-environment: juno_typing
          auto-activate-base: false
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test the python wrapper using base_juno_pipeline.
        shell: bash -l {0}
        run: python ./tests/test_juno-typing.py