name: Build and release
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  bump-version:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: juno_typing
          token: ${{ secrets.RELEASE_TOKEN }}
