name: Build and release
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  bump-version:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history to make sure release-please can access the latest release tag
          fetch-depth: 0
          fetch-tags: true
          
      - name: Release with release-please
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: juno_assembly
